sudo: required
language: php
services:
- docker
os:
- linux
before_script:
- composer create-project --prefer-dist laravel/laravel source/laravel
- docker --version
- docker-compose --version
script:
- docker-compose build
- docker images
- docker-compose up -d
- sleep 10
- docker ps
- echo "127.0.0.1 laravel.dev" > /etc/hosts
- curl --retry 10 --retry-delay 5 -v http://laravel.dev
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker push vietdien2005/laravel_circleci
env:
  global:
  - secure: YG8xxDUwxx9TMuRlLuYZOqaqZ9ueNezEdjZlY9Cu5DHYFWEol/qPEJCCVwU2heNzQIqB9mEMl4tOdImX2y4NcM4sjVbFZFJo0BgEhVpKb5/lfh62Mm+LURYWLxZaHLzIuAPPdwfMVu3V2zcwOTMqG2lsBUVZssZErRtKKRStI4tCJc6M0fB3Bz9Bpbp8R0gAXc5yBXgwMLqu6/oPHzK73LsEIdBCNaW5jQBblmLdP9wRo1wy8ebrpMnOy8kG+GWAuh3jPdXy5p/57UkTDTXKXeAA+eTTgz8Sfny9iIWdzY7i7+92/eUha/zULblYdjf9OSmd7Mdkh1mA+MK8Wp5K46pDEyABbPpZCz/ZWtm1eS8EGLc92l0ePqr/HMvfFxeQmfjJOGUx1cP72uAxc7VoebqF4jCVOkoIDWouow/EAoIEgexkTLh8ZRYc6Ny2uP4Bl5b1ZXZq9n98dmd5EjCJWGXeUl85dunpK+PwAhIar/7bz2xX+fk77SI1PcNmJ3T7bPCRBta9IWdut1xbOvOwMuWGLZw1mn5XlX3bBCTE8Wx1pRpzzTc3uLO5ICRcLCtsK5b04ERqQBRJyPuW7euhhwEfq9EzzOSG8RAs1fQA1nyFcFNv9lbQsEoOo3pDj/IP95VJgC69563RJ5xwhB0nB+YS9gJI5RXcBl2SsHK0nd8=
  - secure: mr2P1eXtSpPL0i2pJMWNloCdybF7nEuYIyENTvIYIhAW0m6RbcCUvb2bjPb3MckYBdmwP7GPc0jmxOjuP6zUGSivTByYlSjGNVkSG9rIAuZWggJwgWw9+aUFriQ1IbazVwCV8x1llgx8LLGi03df1Io7fC0+aGPwpuNhZK6+0OxA6ewx3aAJr6+6hujbTtl7TY33kjqzXbGqwZOCLd0o0xPs1VybAle1CulOv7+6qA3Eko2U63Op6jZB66hjaomSKgA5gQL04L/1sHdUNrH9npoVEZfEwKrEWSNidWLinAersUblVGBBHS55zw8ZGxa5fyzYSnmqHMhJB99HPNG19FVCrYgXBLkBXhTorZ5lExJ0MmoC5YiB9McHKCzkwT94PiNGI9P3dqbH2EH7RrlnCEThrtIS9Ei0ceIg49lO9HlEKuxpWRcaq4X5fP8PeNZ+mPlFwM4iMulXpNjaF4x+aXhy+kKBbZqb1TZluMbhnSRu13TFluG0XeSSEmp6kAj9E2sPEqM5SkB0RkimmIWW9WOeDv+xx442B+DRAj5PhFqohobmoWhdOp3WvPgHv9XS1kCaUtcm8pzv33sRB78CU5VRs8jGMlxeT32frQ5gCqXnB8N7Bpi57FdSYl0RJusxkmFAOluXzeiyq4sgBtwBPXePbQNqnAbXUrh2mpXd1I0=
  - secure: HpILD+AW2da/MvG5rxN1BoZOW91KKRkXUePdzuo4UdCzEcuaQm3DqPGMLN/wO6fWl/i4AqmFdGggGSiiBDrd0Mr2jnlhkaITlNykiAtcrfDDEny+WDQPgd/HP0hICWMdprYDpOTUzxo0BdWR9TXzjHTvm5+sw8w2E/N8mCOisCYohcZsIRXWhDGUxKoTKn7QtvCWPw3LPcwtwVXb7LrFemNZuUV9g9RvYUFbbL7LhhKe2AOItcuQGHrjvNIbwbqmN3zke0r9Tm68RCY8a9k+icjPvgE5r4SLYfSCm36FfE09GC1PuDGqT8MXHlznCtOl8Rjh0fYiCHLb+qkd/f+Hy+4kd1xGVd6k5dvpc54j0qbPHo2Lz2zabqe34SjvTnlEcbaUfSL0CXZLVi7CgvkgWyVdJ/cvZKUFHyyZVxyqUIyBsN/EFcdlHl2OSxkEjfXWdkx5TLG7i6Z5UReZT29THhO+aSvEhZ162KvJP5jLO0wfqutJRmHscQLbLc/rA58YHno8h7JaGvVzZn/xQgm8XLzAmtRMqJ+Q9ZKwIgoA3JqNBUeB0PDPn6mGGWapBIj4TGCixHRbWIjrhwmUy/H8Mrr9CnWmy+EQotBX1ntN4zeq3NosopqhXlCmtXe+PCcMQ7JWVDFQeusbYJwMsgVC8jZhnQvKLHKf1UdA6CSxdU8=
notifications:
  slack:
    rooms:
      secure: ScfpB3yV0y+HGpERfA3yO6GRJRVfgnwIjiDKpVU5ovcahK80l6oLGl06zSseLHlhxc/QAEKQbWg/76PzSdXT4D7IIcwgoEV4AtQpPj7QrWtI+95IhV7oIw9SYdbKCUK91vouL/qcjHNco55JaPOcRXPO+0o1bd17mSBuh971hA0nv2EeHkA6CP6hGU0cbG8a0OjSmsZ7e1I1mFfAunun19eMHH2MsskkYmxz2/ABU0QsZ3RWkonPl2uL+uCaTlF6Rual7TIE/zVBfkdj09OinVPZYZCOcuqAb7zveu/Ax3WrZb5ZMEP4R2pQpRS8Kbe6EDwHRSXwk6st6Y/8VMMF5MogYARujI6o2UKRdwkdjpiyj/QK4DedIzGedcPmrzO0vUuDTrt7LedmYOqC/BOc75LFPKNf5pgy5xueLx7OHX0hGuDZXXb68pixkQmf4V4VbCRbaRKSDdNVoSp0dPHnHfJP51jDRQ9HPSL2LgXDsap7nTnxXYu66Y/cWd0iflhE7J7redV37Bo/PyWxKgkSmzMQWCCnc/ueI0f+oD9i0F3HzFUrnkaJwqhZWInjhg+xhz26bf/4yWwT++a9iKBX8doP+SHjCVtKiD+fzElypCFtry9GgaqNvJ3SP05tPJtPAmEx+naBAND9bpRN4zs5MsVgSXg5w44k43H72yT0CLA=
