version: '2'

services:
    laravel_circleci:
        build: 
            context: ./build
        image: vietdien2005/laravel_circleci:latest
        ports:
            - "80:80"
        volumes:
            - ./source:/var/www/html
            - ./build/nginx/conf.d:/etc/nginx/conf.d
            - ./build/nginx/logs:/var/log/nginx
            - ./build/supervisor/conf.d:/etc/supervisor/conf.d
            - ./build/supervisor/laravel:/var/log/laravel
